### ISSUE TITLE
libSodium and PHP 7.2

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/jose#161]
It seems that libSodium will be integrated as a core module for PHP 7.2 (see https://wiki.php.net/rfc/libsodium).
PHP 7.2 should be released by the end of the year 2017.

This will be a great opportunity for this library to drop old PHP versions and pure PHP implementations and take advantages of this new module.

**Comment by skyzyx** [comment]
Actually, I'm in the market for a more performance-focused JWT library as the current library I'm using (https://github.com/lcobucci/jwt) has a significant performance impact on my realtime API. Is there a way to use libsodium with PHP 7.1.x _today_ for faster performance (since my migration to 7.2 will _definitely_ happen)? Or is https://github.com/bukka/php-crypto still my best bet for high performance?

**Comment by moderndeveloperllc** [comment]
@skyzyx libsodium is already [a PECL extension](https://pecl.php.net/package/libsodium) if that's what you are looking for. I use it already for hashing passwords with the Argon2i algorithm.

In theory, you could write classes with libsodium functions to be used with the `Signer`, `Verifier`, etc classes. @Spomky has done a great job in making sure that everything is written to interfaces, not concrete classes. That would be a pretty tall order; though I'm sure @Spomky would appreciate you doing the work for him!

@Spomky, since everything is written to interfaces, I'm not sure if you need to drop older implementations or just add new, preferred by default, `Algorithm` classes that utilize the new libsodium extension. Even though the namespace will change, I'm guessing that you are already working on this?

**Comment by Spomky** [comment]
Hi @skyzyx,

@moderndeveloperllc is right: you can write and use your own algorithms by implementing the dedicated interface.

Before doing that, can you tell me which algorithm you are using?

As https://github.com/lcobucci/jwt provides no encryption algorithms, I understand, you are using only signature algorithms.
All algorithms (`ESxxx` included) are already optimized on PHP 7.1. See [the tables on this page](https://github.com/Spomky-Labs/jose/blob/master/doc/Performance.md#signatureverification-operations). Just run `php ./tests/Performance/SignaturePerformance.php` to see how fast is this library on your platform.

The Crypto extension you mentioned is only useful for AES-GCM encryption algorithms on PHP 5.x or 7.0. Already optimized on PHP 7.1

**Comment by Spomky** [comment]
Hi @moderndeveloperllc,

The `v7` branch already uses the version 2.x of the extension through the [libSodium compat library](https://github.com/paragonie/sodium_compat).
It works fine on my computer (PHP 7.1) as well as tests on Travis-CI (see https://github.com/Spomky-Labs/jose/blob/v7/install_php_ext.sh to see how the extension is installed).

libSodium is used for the EdDSA signature algorithm (curve Ed25519) and ECDH-ES* key encryption algorithms (curve X25519). It replaces the two third party extensions suggested in v6 (see [the 1st](https://github.com/encedo/php-ed25519-ext) and [th 2nd one](https://github.com/encedo/php-curve25519-ext)).

I have very good results: approx 350 µs/operation (see [this partial result table](https://gist.github.com/Spomky/af993098b50432c88633620687d6c2d5)).
In this table, you will see that the encryption process using other curves (`P-256`, `P384` and `P-521`) are very slow (between **35 and 80 ms** i.e. 100 ~ 250 times slower).
I am still looking for a better way to support those curves.

**Comment by Spomky** [comment]
Hi @schodemeiss,

I made internal changes on RSA signature and encryption algorithms.
Before those changes, these algorithms had to convert keys from JWK to PEM. Then PEM keys were used by the openssl functions.
Now the JWK is directly used. I replaced the key conversion and openssl calls by simple pure PHP and GMP calls.

The result is that the algorithms are faster: approx 20% faster than before.

I have to do the same modifications for the EC algorithms. I will try to integrate only the needed parts from the mdanter/phpecc lib and perform.

**Comment by schodemeiss** [comment]
This is great news indeed. Any ETA on when 7.0 might be released? I guess when PHP 7.2 releases?

**Comment by Spomky** [comment]
Hi @schodemeiss,

If think I will tag the first alpha release by the end of November.
The minimal PHP version should be 7.1. The package uses [`paragonie/sodium_compat`](https://github.com/paragonie/sodium_compat) for the missing PHP 7.2 features.

Regarding the ASN.1 issue, I will try another library (e.g. https://packagist.org/packages/sop/asn1).

**Comment by Spomky** [comment]
Closing as libSodium is now fully integrated on the v7 branch.
Please follow [Version 7.0](https://github.com/Spomky-Labs/jose/milestone/8) or https://github.com/Spomky-Labs/jose/issues/152 to get information about the new major release.
