### ISSUE TITLE
PHP 7.2 incompatible library. Perhaps remove or use something else?

### ISSUE THREAD

**Issue by schodemeiss** [Spomky-Labs/jose#180]
The PHPASN1 library isn't compatible with PHP7.2. If no fix is found for this, is there potential to remove this library if it's not actually required or a minor feature (I'm unsure).

Relations to:
#https://github.com/fgrosse/PHPASN1/issues/65

**Comment by Spomky** [comment]
Yes, there is a potential issue here.
The only way I see is to limit the current stable branch (`v6.x`) to PHP<7.2.

For the next major release, this dependency is not installed anymore as `mdanter/ecc` will be recommended and not required (see https://github.com/Spomky-Labs/jose/blob/v7/composer.json#L46).

The main reasons for that are:
* `mdanter/ecc` is  useless for signature operation with a PHP 7.1 environment (the minimum requirement for that new version)
* because `mdanter/ecc` is a pure PHP library, encryption operations are very slow (100 ~ 500 times slower than other encryption algorithms).

libSodium provides a [scalar multiplication interface](https://download.libsodium.org/doc/advanced/scalar_multiplication.html). I will try to use it. As this extension will be part of the PHP 7.2 core (see #161), it looks like this is the best alternative.

**Comment by Spomky** [comment]
Waiting for https://github.com/fgrosse/PHPASN1/pull/66 to be merged and the library to be tagged.

The project now integrate a custom implementation of the phpecc library. It contains only the minimum required to compute ECDH encryptions.
This will allow to move forward when the ASN.1 library major version will be released.

**Comment by Spomky** [comment]
Done
