### ISSUE TITLE
Better curl error messages for ^6.0

### ISSUE THREAD

**Issue by fkupper** [Spomky-Labs/jose#316]
@Spomky Can you make a ^6.0 release with the changes from https://github.com/Spomky-Labs/jose/pull/314? I am currently running php 5.6.

Thanks.

**Comment by Spomky** [comment]
Hi @fkupper,

Sorry for the late answer, I am very busy this month.
I will take care of it.

**Comment by fkupper** [comment]
Hi @Spomky,

Never mind, this is not a killing issue. Do it when you can.

Thanks for the awesome library.

**Comment by Spomky** [comment]
You are welcome.
It is now done. Tagged `v6.1.7`.
Please note that this library will be marked as deprecated by the end of the year.
It will only receive security fixes up to end of 2019.

When your application will be able to run on PHP 7.x, you should really consider to use the new [JWT Framework Project](https://github.com/web-token/jwt-framework) instead of this library.

**Comment by fkupper** [comment]
Thanks for the warning, I am aware of the lifespan.
