### ISSUE TITLE
Export Util\GCM to new repo

### ISSUE THREAD

**Issue by Minishlink** [Spomky-Labs/jose#97]
Hello,

I use your GCM encryption polyfill for my [web-push](https://github.com/Minishlink/web-push) library (thanks!). jose is quite a big dependancy for "just" this part of the library. Would you mind exporting the class Util\GCM to a standalone repository?

**Comment by Spomky** [comment]
Hi,

This is a good idea.
Lot of developers may be interested as other projects pointed this implementation too (see https://github.com/phpseclib/phpseclib/issues/47#issuecomment-212580067).

I think it will be available by the end of the week. I will let you know when done.

**Comment by Spomky** [comment]
Hi,

As announced earlier, I created a new repository: https://github.com/Spomky-Labs/php-aes-gcm

This library is not yet marked as stable. I am added some tests for the moment.
I close this issue here but we can discuss directly on the project repository or on [Gitter](https://gitter.im) if needed.

Thanks and Regards.

**Comment by Minishlink** [comment]
Thank you !
